Share-Free2/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Share_Free.Domain;
using Share_Free.Services;

namespace Share_Free.Controllers
{
    [Route("[controller]")]
    [Authorize]
    public class CommentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("[action]")]
        public IActionResult ModifyComment([FromForm] string message, [FromForm] int commentId)
        {
            CommentService cService = new CommentService();
            string username = HttpContext.User.FindFirst("Username").Value.ToString();
            bool isAdmin = Convert.ToBoolean(HttpContext.User.FindFirst("IsAdmin").Value.ToString());
            List<Comment> userComments = cService.GetAllComments();
            foreach (var comment in userComments)
            {
                if ((username == comment.Username || isAdmin == true) && commentId == comment.Id )
                {
                    cService.ModifyComment(message, commentId);
                    break;
                }
            }

            return RedirectToAction("Index", "Home");

        }

        [HttpPost("[action]")]
        public IActionResult CreateComment([FromForm(Name = "message")] string message, [FromForm(Name = "postId")] int postId)
        {
            // username missing
            CommentService cService = new CommentService();
            string username = HttpContext.User.FindFirst("Username").Value.ToString();
            cService.CreateComment(username, message, postId);

            return RedirectToAction("Index", "Home");
        }


        [HttpPost("[action]")]
        public void DeleteComment([FromForm] int commentId)
        {
            CommentService cService = new CommentService();
            string username = HttpContext.User.FindFirst("Username").Value.ToString();
            bool isAdmin = Convert.ToBoolean(HttpContext.User.FindFirst("IsAdmin").Value.ToString());
            List<Comment> allComments = cService.GetAllComments();
            foreach (var comment in allComments)
            {
                if ((username == comment.Username || isAdmin == true) && commentId == comment.Id)
                {
                    cService.DeleteComment(commentId);
                }
            }
        }


    }
}

Share-Free2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Share_Free.Models;
using Share_Free.Services;

namespace Share_Free.Controllers
{
    public class HomeController : Controller
    {


        


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MyGroups()
        {
            ViewData["Message"] = "You can see the the groups you are in, here.";

            return View();
        }

        public IActionResult MyAccount()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }


        // Lets user create new Post
        [Authorize]
        [HttpPost]
        public IActionResult CreatePost([FromForm(Name = "title")] string title, [FromForm(Name = "description")]string description)
        {
            // username missing
            PostService pService = new PostService();
            string username = HttpContext.User.FindFirst("Username").Value.ToString();
            pService.CreatePost(username, title, description);

            return RedirectToAction("Index", "Home");
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Share-Free2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Share-Free2/Views/Home/Index.cshtml
@model PostModelList
<head>
    <script src="~/js/site.js" defer></script>
    <link href="~/css/site.css" rel="stylesheet" />

</head>

@{
    ViewData["Title"] = "Home Page";
}
@using Share_Free.Services
@using Sharing_Free.Domain
<!--Search bar-->
<body>
    <h3>Welcome!</h3>

    <!-- The Posts -->
    <h1>Posts</h1>
    <h5>New Post</h5>
    <div class="createpost">
        <button onclick="createPost()">Create New Post</button>
        <div id="createPostForm" class="hidden">
            <label>Title:</label>
            <input type="text" name="title" />

            <label>Description:</label>
            <input type="text" name="description" />

            @*<input type="text" id="getUsernamePost" name="username" value="@Context.User.FindFirst("Username").Value.ToString()" hidden />*@


            <input type="submit" onclick="" value="CreatePost" />

        </div>

    </div>

    <div class="post_container">
        @{
            PostService pService = new PostService();
            List<Post> allPosts = pService.GetAllPosts();
            CommentService cService = new CommentService();
            var allComments = cService.GetAllComments();
            foreach (var post in allPosts)
            {
                <div id="parentDivPost">
                    <div id="postdiv_@post.Id">
                        <h2>@post.Title [@post.Id] </h2>
                        @*<button onclick="deletePost(@post.Id)"></button>*@
                        <img src="~/images/garbage2.png" onclick="deletePost(@post.Id)" />
                        <input type="number" id="postId_@post.Id" name="PostId" value="@post.Id" hidden />
                        <p>
                            @post.Description
                            <small>By: @post.Username @post.Date</small>

                            <div class="createpost">
                                <img src="~/images/newPost.png" alt="Modify Post" onclick="modifyPostForm(@post.Id)" />
                                <div id="modifyPostDiv_@post.Id" class="hidden">

                                    <input id="modifyPostId_@post.Id" type="number" name="modifyPostId" value="@post.Id" hidden />

                                    <label>Title:</label>
                                    <input type="text" name="modifyPostTitle" id="modifyPostTitle_@post.Id" />
                                    <label>Description:</label>
                                    <input type="text" name="modifyPostDescription" id="modifyPostDescription_@post.Id" />

                                    <button onclick="modifyPost(@post.Id)">Modify</button>

                                </div>
                            </div>
                        </p>
                    </div>

                    <h3>Comments:</h3>
                    <div id="list_comments_div">
                        <button onclick="test(@post.Id)">Create New Comment</button>
                        <form asp-controller="Comment" asp-action="CreateComment" method="post" id="createCommentForm_@post.Id" class="hidden2">
                            <label>Message:</label>
                            <input type="text" name="message" />
                            <input type="number" name="postId" hidden value="@post.Id" /> @*passing postId to controller*@

                            <input type="submit" value="CreateMessage" />
                        </form>
                        @{
                            foreach (var comment in allComments)
                            {
                                if (comment.Post_Id == post.Id)
                                {
                                    <div id="parentDivComment">
                                        <div id="commentdiv_@comment.Id">
                                            <h4>
                                                [@comment.Username] [ @comment.Id ]
                                                <img src="~/images/garbage2.png" onclick="deleteComment(@comment.Id)" />
                                                <img src="~/images/newPost.png" onclick="modifyComment(@comment.Id)" />
                                            </h4>
                                            <form id="modifyCommentForm_@comment.Id" class="hidden2" asp-controller="Comment" asp-action="ModifyComment" method="post">
                                                <input type="number" name="commentId" value="@comment.Id" hidden />
                                                <label>Modified Message:</label>
                                                <input type="text" name="message" />

                                                <input type="submit" value="Modify Comment" />
                                            </form>
                                            <p><small>@comment.Message @comment.Date</small></p>
                                            @* delete comment *@
                                            <input type="number" name="commentId" value="@comment.Id" hidden id="getCommentId_@comment.Id" />
                                        </div>
                                    </div>

                                }
                            }
                        }
                    </div>
                </div>
                
            }
        }
    </div>
</body>

Share-Free2/Views/Home/MyGroups.cshtml
@{
    ViewData["Title"] = "MyGroups";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>